---
- name: Creating user {{ username }}
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    createhome: "{{ createhome | default('no') }}"
    uid: "{{ uid | default(omit) }}"
    home: "{{ home_dir_prefix | default('/home') }}/{{username}}"
  register: cur_user

- name: Create groups
  group:
    name: "{{item}}"
    state: present
  with_items: "{{ user_groups }}"
  when: user_groups is defined

- name: Creating user {{ username }}
  user:
    name: "{{ username }}"
    groups: "{{ user_groups }}"
    append: yes
  when: user_groups is defined


- name: Set user linger
  shell: "mkdir -p /var/lib/systemd/linger && touch /var/lib/systemd/linger/{{username}}"
  when: (enable_linger is defined) and enable_linger


- name: Allow {{ username }} to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  when: (enable_sudo is defined) and enable_sudo


- name: Create SSH config directory
  file:
      path: "{{ cur_user.home }}/.ssh"
      state: directory
  when: (add_authorized_keys is defined) and add_authorized_keys


- name: Set authorized key took from file
  authorized_key:
    user: "{{username}}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  when: (add_authorized_keys is defined) and add_authorized_keys

- name: Make {{username}} the owner of the home directory.
  file:
    path: "{{ home_dir_prefix | default('/rw/home-') }}{{username}}"
    owner: "{{username}}"
    group: "{{username}}"
    recurse: yes
