---
- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ mounts | map(attribute='path')}}"
  register: dirs
  when: mounts is defined

- name: "Mount"
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ 'mounted' if item.mounted else 'unmounted' }}"
  loop: "{{ mounts }}"
  register: mounts_res
  when: mounts is defined

